Repository ovh-ux/ovh-module-office, pull requests merged in 2018-11, with the labels that each got.

#64 Update readme
  README.md
Labels: enhancement

#62 refactor(components.chartjs): use chartjs from wuc
  src/microsoft/office/license/consumption/CONSUMPTION.html
  src/microsoft/office/license/consumption/microsoft-office-license-consumption.controller.js
Labels: :santa: one-manager, quality check ok

#74 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug
